version: 2

updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@primer/css"

  - package-ecosystem: "github-actions"
    directory: "."
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    groups:
      dependencies:
        patterns:
          - "*"
