# Changes here will be overwritten by Copier
_commit: 06010c1
_src_path: gh:ttoino/templates
description: A website that shows the top 100 github users per country.
name: top-commiters
project_type: sveltekit
tailwind: false
tests: false

